### PR TITLE
Added Pequenio to the theme list.

### PR DESCRIPTION
**Pull request by sergiotarxz**
Hi team, I would like to publish a fork I did from the theme Micro, I waiting to make a brand new theme from that base, for now it looks very similar. I want to keep and improve the simplicity where possible I choose to make a fork since some changes are controversial and cannot be merged into Micro easily but have some sense for me and my user base.

I hope forking doesn't suppose a problem for the authors.

The original repo was licensed under MIT and I choosed to license my changes under GPL but if the Micro authors want some specific patch of my code I could relicense the change under MIT for Micro distribution.

Best regards, Sergiotarxz. 

@dignajar

### CODE REVIEW

**Comment by clickwork-git** [comment]
As far as I know the licence MIT cannot become GPL. I will have a look at it.

**Comment by sergiotarxz** [comment]
> As far as I know the licence MIT cannot become GPL. I will have a look at it.

https://softwareengineering.stackexchange.com/questions/105912/can-you-change-code-distributed-under-the-mit-license-and-re-distribute-it-unde I took I was able to do it from here.

**Comment by sergiotarxz** [comment]
I do not want to cause problem, If I can not use GPL I will use the MIT license.

**Comment by clickwork-git** [comment]
MIT declares:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

But it seems that the licence can be extended. Anyway, I would prefer if you use MIT.

Why do you want GPL?

**Comment by sergiotarxz** [comment]
> MIT declares:
> 
> > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
> 
> But it seems that the licence can be extended. Anyway, I would prefer if you use MIT.
> 
> Why do you want GPL?

I want GPL since it forbids further distributing the changes with privative licenses but I am able to distribute under MIT.

**Comment by clickwork-git** [comment]
Let's see what @dignajar says.

**Comment by sergiotarxz** [comment]
> Let's see what @dignajar says.

Ok, he is the copyright holder of Micro so his opinion is the most important I think.

**Comment by dignajar** [comment]
Hi guys, sorry for my late answer, I'm ok with the change to GPL.

**Pull request merged**
